apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fdeocf6sw-python
  janus-idp.io/tekton: fdeocf6sw-python
  backstage.io/kubernetes-id: fdeocf6sw-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fdeocf6sw-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
