apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: fdeocf6sw-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:322fea6c857cf347f890ffa72606ebb9e77c7a07@sha256:6b066f5ad7c4488f41a48fe7be9c5c3ad3cc1d00c35ebc2d131524cd88e075ff
          name: container-image
